In [1]:
import pandas as pd
import random

In [2]:
datos = {
    "nombre": ["Ana", "Luis", "Carlos", "María", "Pedro"],
    "edad": [18, 20, 19, 21, 22],
    "carrera": ["Sistemas", "Derecho", "Medicina", "Arquitectura", "Contabilidad"],
    "promedio": [9.5, 8.7, 9.0, 8.5, 7.9]
}

In [3]:
df = pd.DataFrame(datos)

In [4]:
df.head()

   nombre  edad       carrera  promedio
0     Ana    18      Sistemas       9.5
1    Luis    20       Derecho       8.7
2  Carlos    19      Medicina       9.0
3   María    21  Arquitectura       8.5
4   Pedro    22  Contabilidad       7.9

In [5]:
df.shape

(5, 4)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nombre    5 non-null      object
 1   edad      5 non-null      int64
 2   carrera   5 non-null      object
 3   promedio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [7]:
df.describe()

            edad  promedio
count   5.000000  5.000000
mean   20.000000  8.720000
std     1.581139  0.593296
min    18.000000  7.900000
25%    19.000000  8.500000
50%    20.000000  8.700000
75%    21.000000  9.000000
max    22.000000  9.500000

In [8]:
df["promedio"].mean()

np.float64(8.72)

In [9]:
df.sort_values(by="promedio", ascending=False)

   nombre  edad       carrera  promedio
0     Ana    18      Sistemas       9.5
2  Carlos    19      Medicina       9.0
1    Luis    20       Derecho       8.7
3   María    21  Arquitectura       8.5
4   Pedro    22  Contabilidad       7.9